version: 0.2

env:
  secrets-manager:
    S3_BUCKET: "trivia-deploy-secrets:trivia_s3_bucket"

phases:
  install:
    commands:
      - pyenv install -s 3.7.0
      - pyenv global 3.7.10

  build:
    commands:
      - sam build
      - sam deploy --no-fail-on-empty-changeset
      - cd front-end-react
      - npm install
      - npm run build
      - aws s3 sync --acl public-read build $S3_BUCKET
      # - pylint --fail-under=8 trivia-app/back-end-python/gameactions/app.py
      # - pytest trivia-app/back-end-python/tests/unit --junit-xml=unittests.xml --cov-report=xml --cov=gameactions --cov-branch